services:
  api:
    restart: unless-stopped
    build: .
    ports:
      - "10001:3000"
    environment:
      - NODE_ENV="production"
    volumes:
      - /home/ubuntu/running/logs/freecodecamp-headerparser:/program/logs